### ISSUE TITLE
Folders stay on local machine if VSCode is closed not gracefully

### ISSUE THREAD

**Issue by RandallFlagg** [garethflowers/vscode-portable#13]
I notice that 2 folders are created on local machine when staring the app. 1 is at the user profile and 1 is at the %APPDATA% folder. If the VSCodePortable.exe is close in a not graceful way those 2 folders stay on the machine.

**Comment by thwbn** [comment]
had the same issue! 
even if you close vscode portable gracefully it will DELETE the extensions folder on the local machine %userdata%\.vscode\extensions\*.*

but when I focused one extension in the %userdata%\.vscode\extensions\ which had a too long folder path - I changed that path first step by step and deleted that path with all sub folders successfully. Now it works fine so far: BUT the vscode protabel deletes the extensions in %userdata%\.vscode\extensions\*.* folder. So: what if you run vscode on a portable machine, wich runs an own vscode.exe loacaly? I am afraid that I would delete the whole folder %userdata%\.vscode\extensions\ with all of the extensions in it. 

This wouldn't be appreciaded by the PC owner, I guess.

WIN 10, 64bit V1607 Build: 14393.222 vscode: 1.53 voscode-portbale-master: 1.52

thnkas for fixing this

Thorsten

**Comment by garethflowers** [comment]
This should now be resolved in [v1.6](https://github.com/garethflowers/vscode-portable/releases/tag/v1.6) - now that issues Microsoft/vscode#8990 and Microsoft/vscode#12129 have been resolved.

All extensions and cache files are now referenced locally inside the portable application directory, instead of being created on the client machine.
