### ISSUE TITLE
x64 VSCODE

### ISSUE THREAD

**Issue by tschertel** [garethflowers/vscode-portable#29]
Can I use x64 version?

**Comment by LightDestory** [comment]
Reading the launcher settings it seems that there aren't platform entries, so yes this portable enviroment can work with x64bit version. BTW a portable version means that you run it on differents pc:
using x86 verison you have 100% chance of run (it will run always)
using x64 version you have a lower chance (due to the possibility to use a x32 bit pc)

**Comment by garethflowers** [comment]
[v1.15.1](https://github.com/garethflowers/vscode-portable/releases/tag/v1.15.1) has just been released - which includes both x32 and x64 bit versions of VSCode. It will automatically run the most relevant one based on your system.
